version: '3.8'

services:
  backend:
    image: ${DOCKER_REGISTRY-}teledokapi
    build:
      context: .
      dockerfile: TeledokAPI/Dockerfile
  db:
    image: postgres:15
    container_name: postgres-db
volumes:
  postgres_data: